### Ejercicio 1.5 - Permutaciones

Una función recursiva que genera e imprime todas las permutaciones de un arreglo se puede plantear
de la siguiente manera:

~~~python
def permutaciones(x,ini,fin):
~~~
   genera las permutaciones del arreglo x desde el elemento
   con índice ini hasta el elemento con índice fin  
   
- Si $ini$ es igual a $fin$ implica que se pide la permutación de un solo elemento, y en ese momento se imprime
  todo el contenido del arreglo
- De lo contrario, para todos los elementos $x[i]$ con $i$ desde $ini$ hasta $fin$ ($fin$ incluido) se hace lo siguiente:
                 . se intercambia el valor del i-ésimo elemento con el inicial
                 . se llama recursivamente a la función permutaciones con el 
                    índice del primer elemento incrementado: permutaciones(x, ini+1, fin)
                 . Se vuelven a restaurar los valores del elemento inicial con el i-ésimo

Implemente la función "permutaciones" que imprima todas las permutaciones de un arreglo de entrada. Probar su función con arreglos de tamaño 1, 3 y 5.

In [ ]:
# librerias
import numpy as np

In [ ]:
"""=============================================================================
permutaciones(x,ini,fin)
algoritmo que imprime todas las permutaciones del arreglo 
x entre las posiciones ini y fin
============================================================================="""
def permutaciones(x,ini,fin):
  # check del input 
  assert ini>=0 and fin<=len(x)
  # condicion de impresion
  if ini == fin:
    print(x)
  else:
    # recursion
    for i in range(ini,fin+1):
      (x[i],x[ini])=(x[ini],x[i])
      permutaciones(x,ini+1,fin)
      (x[ini],x[i])=(x[i],x[ini])

In [ ]:
# arreglos para hacer test
A = np.array([48,71,69])
B = np.array([20,30,40,50])
C = np.array([33,44,12,56,45])
D = np.array([123,132,213,231,312,321])

In [ ]:
permutaciones(A,0,2)

[48 71 69]
[48 69 71]
[71 48 69]
[71 69 48]
[69 71 48]
[69 48 71]


In [ ]:
permutaciones(B,1,3)

[20 30 40 50]
[20 30 50 40]
[20 40 30 50]
[20 40 50 30]
[20 50 40 30]
[20 50 30 40]


In [ ]:
permutaciones(C,0,4)

[33 44 12 56 45]
[33 44 12 45 56]
[33 44 56 12 45]
[33 44 56 45 12]
[33 44 45 56 12]
[33 44 45 12 56]
[33 12 44 56 45]
[33 12 44 45 56]
[33 12 56 44 45]
[33 12 56 45 44]
[33 12 45 56 44]
[33 12 45 44 56]
[33 56 12 44 45]
[33 56 12 45 44]
[33 56 44 12 45]
[33 56 44 45 12]
[33 56 45 44 12]
[33 56 45 12 44]
[33 45 12 56 44]
[33 45 12 44 56]
[33 45 56 12 44]
[33 45 56 44 12]
[33 45 44 56 12]
[33 45 44 12 56]
[44 33 12 56 45]
[44 33 12 45 56]
[44 33 56 12 45]
[44 33 56 45 12]
[44 33 45 56 12]
[44 33 45 12 56]
[44 12 33 56 45]
[44 12 33 45 56]
[44 12 56 33 45]
[44 12 56 45 33]
[44 12 45 56 33]
[44 12 45 33 56]
[44 56 12 33 45]
[44 56 12 45 33]
[44 56 33 12 45]
[44 56 33 45 12]
[44 56 45 33 12]
[44 56 45 12 33]
[44 45 12 56 33]
[44 45 12 33 56]
[44 45 56 12 33]
[44 45 56 33 12]
[44 45 33 56 12]
[44 45 33 12 56]
[12 44 33 56 45]
[12 44 33 45 56]
[12 44 56 33 45]
[12 44 56 45 33]
[12 44 45 56 33]
[12 44 45 33 56]
[12 33 44 56 45]
[12 33 44 45 56]
[12 33 56 44 45]
[12 33 56 45 44]
[12 33 45 56 4

In [ ]:
permutaciones(D,2,5)

[123 132 213 231 312 321]
[123 132 213 231 321 312]
[123 132 213 312 231 321]
[123 132 213 312 321 231]
[123 132 213 321 312 231]
[123 132 213 321 231 312]
[123 132 231 213 312 321]
[123 132 231 213 321 312]
[123 132 231 312 213 321]
[123 132 231 312 321 213]
[123 132 231 321 312 213]
[123 132 231 321 213 312]
[123 132 312 231 213 321]
[123 132 312 231 321 213]
[123 132 312 213 231 321]
[123 132 312 213 321 231]
[123 132 312 321 213 231]
[123 132 312 321 231 213]
[123 132 321 231 312 213]
[123 132 321 231 213 312]
[123 132 321 312 231 213]
[123 132 321 312 213 231]
[123 132 321 213 312 231]
[123 132 321 213 231 312]
